name: ImCircuit CI For Gitea

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-cmake:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build doxygen graphviz build-essential cmake
          sudo apt-get install -y libsecret-1-dev
      - name: Build
        run:  |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE=Release -G Ninja -DIMC_GUI=False
          ninja -C build/ release/ImCircuit.tst
      - name: Run Tests
        run:  build/release/ImCircuit.tst
      - name: Upload artifact
        run: |
          cd build
          mv docs imcircuit
          zip -r "docs.zip" imcircuit
          curl -X POST -F "file=@docs.zip" "http://home.internal:9696/docs/imcircuit"
