name: LCS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-cmake:
    name: Run cmake tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ninja
        run: sudo apt-get install -y ninja-build doxygen
      - name: Build
        run: cmake -S . -B build/ -DCMAKE_BUILD_TYPE=Release -G Ninja
      - name: Run ninja
        run: ninja -C build/ release/LogicCircuitSimulator.tst
      - name: Run the test file
        run: release/LogicCircuitSimulator.tst
